AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  Template para desplegar Lambda Telegram Bot y sus recursos

Globals:
  Function:
    Timeout: 10
    Runtime: python3.11
    MemorySize: 256
  Api:
    Auth:
      DefaultAuthorizer: NONE
    BinaryMediaTypes:  # Add support for binary media types
      - '*/*'
    Cors:  # Enable CORS
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Parameters:
  TelegramToken:
    Type: String
    Description: Token de tu bot de Telegram
  OpenAIApiKey:
    Type: String
    Description: OpenAI API Key
    NoEcho: true

Resources:
  # API Gateway
  TelegramBotApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${AWS::StackName}-api"
      StageName: Prod
      EndpointConfiguration: REGIONAL
      Auth:
        ApiKeyRequired: false
      MethodSettings:
        - HttpMethod: "*"
          ResourcePath: "/*"
          LoggingLevel: OFF  # Disable logging initially
          DataTraceEnabled: false
          MetricsEnabled: false

  # Lambda Function
  TelegramBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: telegram-bot-giobot
      Handler: app.lambda_handler
      CodeUri: function.zip
      Runtime: python3.11
      MemorySize: 256
      Timeout: 10
      Description: Bot de Telegram en Lambda desplegado vía CloudFormation
      Environment:
        Variables:
          TELEGRAM_BOT_TOKEN: !Ref TelegramToken
          OPENAI_API_KEY: !Ref OpenAIApiKey
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiGatewayInvoke:
          Type: Api
          Properties:
            Path: /webhook
            Method: POST
            RestApiId: !Ref TelegramBotApi

Outputs:
  LambdaFunctionArn:
    Description: ARN de la función Lambda creada
    Value: !GetAtt TelegramBotFunction.Arn
  
  ApiGatewayUrl:
    Description: URL del API Gateway para el webhook de Telegram
    Value: !Sub "https://${TelegramBotApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook"