AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  Template para desplegar Lambda Telegram Bot y sus recursos

Globals:
  Function:
    Timeout: 10
    Runtime: python3.11
    MemorySize: 256

Resources:
  TelegramBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: telegram-bot-giobot
      Handler: app.lambda_handler
      CodeUri: function.zip
      Runtime: python3.11
      MemorySize: 256
      Timeout: 10
      Description: Bot de Telegram en Lambda desplegado vía CloudFormation
      Environment:
        Variables:
          TELEGRAM_TOKEN: !Ref TelegramToken
          OPENAI_KEY: !Ref OpenAIApiKey
      Policies:
        - AWSLambdaBasicExecutionRole   # Log a CloudWatch
      Events:
        ApiGatewayInvoke:
          Type: Api
          Properties:
            Path: /webhook
            Method: POST

Parameters:
  TelegramToken:
    Type: String
    Description: Token de tu bot de Telegram
  OpenAIApiKey:
    Type: String
    Description: OpenAI API Key
    NoEcho: true

Outputs:
  LambdaFunctionArn:
    Description: ARN de la función Lambda creada
    Value: !GetAtt TelegramBotFunction.Arn