name: Deploy Lambda Function with CloudFormation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Test AWS credentials
      run: |
        aws sts get-caller-identity

    - name: Install dependencies
      run: |
        pip install awscli boto3

    - name: Create deployment package
      run: |
        zip -r function.zip lambda_function.py test_lambda.py requirements.txt

    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \
          --template-file infraestructure/cloudformation/template.yaml \
          --stack-name telegram-bot-stack \
          --capabilities CAPABILITY_IAM \
          --parameter-overrides \
            OpenAIKey=${{ secrets.OPENAI_KEY }} \
            TelegramBotToken=${{ secrets.TELEGRAM_TOKEN }} \
          --region ${{ env.AWS_REGION }}

    - name: Clean up
      run: |
        rm function.zip