name: Deploy Telegram Bot Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: giobot        # <-- Match con tus environment secrets

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # (Opcional) Setea Python si tu build/test lo requiere antes del paquete

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install dependencies for Lambda
      run: |
        # Create build directory
        BUILD_DIR="build"
        rm -rf "$BUILD_DIR"
        mkdir -p "$BUILD_DIR"
        
        # Copy Lambda code and requirements
        cp lambda/app.py "$BUILD_DIR/"
        cp lambda/requirements.txt "$BUILD_DIR/"
        
        # Install dependencies in Lambda-compatible environment
        docker run --rm \
            -v "$PWD/$BUILD_DIR":/var/task \
            public.ecr.aws/lambda/python:3.11 \
            /bin/bash -c "
                pip install --upgrade pip && \
                pip install -r requirements.txt -t . && \
                rm -rf __pycache__ && \
                find . -type d -name "__pycache__" -exec rm -rf {} +
            "
        
        # Create deployment package
        cd "$BUILD_DIR"
        zip -r ../function.zip .
        cd ..

    - name: Package Lambda with CloudFormation
      run: |
        aws cloudformation package \
          --template-file infraestructure/cloudformation/template.yaml \
          --s3-bucket giobotlambdaaws2025 \
          --output-template-file packaged-template.yaml

    - name: Deploy Lambda with CloudFormation
      run: |
        aws cloudformation deploy \
          --template-file packaged-template.yaml \
          --stack-name telegram-bot-stack \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides TelegramToken=${{ secrets.TELEGRAM_TOKEN }} OpenAIApiKey=${{ secrets.OPENAI_API_KEY }}

    # (Opcional) otros pasos post-deploy (notificaciones, validaciones, etc)