name: Deploy Lambda Function

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install dependencies
      run: |
        pip install awscli boto3

    - name: Create deployment package
      run: |
        zip -r function.zip lambda_function.py test_lambda.py requirements.txt

    - name: Update Lambda Function
      run: |
        aws lambda update-function-code \
          --function-name telegram-bot-lambda \
          --zip-file fileb://function.zip \
          --region ${{ env.AWS_REGION }}

    - name: Update Lambda Function Configuration
      run: |
        aws lambda update-function-configuration \
          --function-name telegram-bot-lambda \
          --environment 'Variables={OPENAI_API_KEY=${{ secrets.OPENAI_KEY }},TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_TOKEN }}}' \
          --region ${{ env.AWS_REGION }}

    - name: Clean up
      run: |
        rm function.zip