name: Deploy Telegram Bot Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: giobot        # <-- Match con tus environment secrets

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # (Opcional) Setea Python si tu build/test lo requiere antes del paquete

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install dependencies for Lambda
      run: |
        cd lambda
        pip install -r requirements.txt -t . --platform linux_x86_64 --only-binary=:all:

    - name: Package Lambda with CloudFormation
      run: |
        aws cloudformation package \
          --template-file infraestructure/cloudformation/template.yaml \
          --s3-bucket giobotlambdaaws2025 \
          --output-template-file packaged-template.yaml

    - name: Deploy Lambda with CloudFormation
      run: |
        aws cloudformation deploy \
          --template-file packaged-template.yaml \
          --stack-name telegram-bot-stack \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides TelegramToken=${{ secrets.TELEGRAM_TOKEN }}

    # (Opcional) otros pasos post-deploy (notificaciones, validaciones, etc)